# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
  - powershell: |
      git submodule update --init --recursive
      scripts/lib/init.ps1 .
      scripts/init.ps1 .
      scripts/lib/restore.ps1 .
      scripts/restore.ps1
    displayName: 'install'

  - powershell: scripts/test.azure-pipelines.ps1
    displayName: 'Run Pester tests'

  - task: PublishTestResults@2
    inputs:
      testRunner: NUnit
      testResultsFiles: 'artifacts/test-result.xml'
      failTaskOnFailedTests: true
