#
# Module manifest for module 'Terraform'
#
# Generated by: jakub.pawlowski
#
# Generated on: 07.02.2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'Terraform.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0.0'

    # ID used to uniquely identify this module
    GUID              = 'f8c3e5a1-7b2d-4c9e-8f1a-3d5b6c7e8f9a'

    # Author of this module
    Author            = 'jakub.pawlowski'

    # Company or vendor of this module
    CompanyName       = 'Holycode sp. z o.o.'

    # Copyright statement for this module
    Copyright         = '(c) 2026 jakub.pawlowski. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Provides helper functions for initializing and managing Terraform state with Azure backends'

    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = ''

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @('powershell-yaml')

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module
    FunctionsToExport = @(
        'Initialize-TerraformLocal',
        'Initialize-TerraformBlob',
        'Initialize-TerraformAzure',
        'Set-AzurePAT',
        'Test-State',
        'Export-EnvConfig',
        'Import-EnvConfig',
        'Get-BackendConfig',
        'Select-Subscription',
        'Get-ConfigVars',
        'Out-TerraformVars',
        'Generate-TerraformVars',
        'ParseErrors',
        'Initialize-EnvConfig',
        'Get-PlanSummary'
    )

    # Cmdlets to export from this module
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport   = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('Terraform', 'Azure', 'Infrastructure', 'IaC')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/qbikez/ps-entropy/blob/master/license.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/qbikez/ps-entropy.git'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable
    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
